export const randomList = [
  'A group of pugs is called a grumble.',
  'Newborn babies have nearly 100 more bones than full-grown adults.',
  'There are 293 ways to make change for a U.S. dollar.',
  'The word dude originated in the 1800s as an insult to men overly concerned with the latest fashion trends.',
  'If your dog\'s feet smell like corn chips, you\'re not alone. The term "Frito Feet" was coined to describe the scent.',
  'The plural of cul-de-sac is culs-de-sac.',
  'The only Blockbuster store in the world that is still operating is located in Bend, Oregon.',
  'The number 4 is the only number with the same number of letters as the meaning of its name.',
  'Goldfish can distinguish the music of one composer from another.',
  'High schools and universities in New Zealand are allowed to keep up to a pound of uranium on the premises for educational purposes.',
  'In 1953, it took 27 hours to create one PEEPS Marshmallow Chick. Today, that same process takes just six minutes.',
  'Bubble gum is pink because that was the only food dye available in the factory where it was made.',
  'The Eiffel Tower leans slightly toward the shade on sunny days.',
  'A group of clowns is sometimes called a giggle.',
  'On Scooby-Doo, Shaggy\'s real name is Norville Rogers.',
  'While an Oscar is of unnamed value to someone who wins (or loses) one, the actual trophy has a raw value of about $600.',
  'The first Hershey\'s chocolate bars with almonds were produced in 1908 because they were cheap to make. The nuts took the place of some of the more expensive milk chocolate, which meant Hershey\'s could keep the price of the candy at a nickel.',
  'According to one study, dunking an Oreo in milk for three seconds gives you the optimal balance of sogginess and structural integrity.',
  'The term “lawn mullet” means having a neatly manicured front yard and an unmowed mess in the back.',
  'The heads on Easter Island have bodies.',
  'Sleeping through summer is called estivation.',
  'Goldfish has a memory span of three seconds.',
  'The katydid bug hears through holes in its hind legs!',
  'A giraffe can go without water longer than a camel.',
  'he pop you hear when you crack your knuckles is actually a bubble of gas burning.',
  'f you went out into space, you would explode before you suffocated because there`s no air pressure.',
  'Donald Duck`s middle name is Fauntleroy.',
  'The highest per capita Jell-O comsumption in the US is Des Moines.',
  'On average, people fear spiders more than they do death.'
]
